#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

name: PR Build

on:
  pull_request:
    branches: [main]

jobs:
  build-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Turn script into an executable
        run: chmod +x detect-secrets.sh
  
      - name: Run the detect secrets script
        run: ./detect-secrets.sh
